spring.application.name=ai-agent

# Server
server.port=8080

# Jira Configuration
jira.base-url=https://2300032396cseh.atlassian.net
jira.email=2300032396cseh@gmail.com
jira.api-token=ATATT3xFfGF0siKQpGv2GH-Kfm1Ccf_F5W1ZO83khcTZznwMoW8sQZHA7lrcN5CUyMLQ1PKwDcg4Xq2rDLwxsKBjkP3XaU7RQXcATvV9U_X9hPRZxvXKSQ6Hpc14ZzKIXxXSgS5peufW8hTbjpll38xj5wgHO4_TGvz_4hq8R93aD-TY1z0HLGg=5BE8AE4B
# Logging
logging.level.com.rcs.aiagent=DEBUG